### PR TITLE
Added menu button

### PR DESCRIPTION
**Pull request by stevenoakley211**
Added the Drop down menu button to Full Calendar Still needs a menu.

### CODE REVIEW

**Review by corgipower — APPROVED** [review]
This looks like a good start

**Comment by Dodgers-42** [comment]
This looks good, this will look great  finished

**Review by Dodgers-42 — COMMENTED** [review]
Looks great so far

**Review by sathyaganesan — APPROVED** [review]
Great job!

**Review by Dodgers-42 — APPROVED** [review]

**Pull request merged**
