### PR TITLE
created editing ability and start/end time in computer list view 

### PR DESCRIPTION
**Pull request by DanielleKoduru**
# PR Title:
Added a start/end time to the one hour block view allowing the user to edit their start and end time slot, working on editing functionality in the pop-up confirmation window.
## Short Description:
I added a start/end time to the one hour block view allowing the user to edit their start and end time slot when submitting a session on the computer list. I am still working on the editing functionality within the pop-up confirmation window. [Link to task](https://trello.com/c/hChuF2fc/27-the-headmaster-can-edit-the-confirmation-pop-up-window)
## Rational/purpose of the feature:
To allow the user to be able to enter/edit the start and end time of session
## Link to relevant user story:
https://trello.com/c/lNakygFb/9-as-a-user-i-want-to-have-the-option-to-check-in-the-mentee-to-session
### Optional: Screenshots of intended state of feature, wireframe, flowchart

# Checklist for author and reviewers:

- Commits are well named and descriptive
- PR is focused on a single problem, is small enough and easy to review
- PR requests were sent to multiple reviewers
- PR is reviewed by more than one team member
- Code is consistenty formatted
- Code is suitably commented on
- There is no duplicate code
- Code tries to follow best practices
- Decide with reviewers if this PR should have tests before merging

### CODE REVIEW

**Review by petevs — APPROVED** [review]
Awesome work! Looks good. I couldn't see anything that needs changing. 

The only thing I wonder is the UX of the submit and edit button. I'm not sure that the edit button is necessary, if the details are not locked and can be changed by the user without clicking the edit button. Maybe the submit button would make more sense as a "save changes" and possibly a cancel button to revert to the original. 

However, I don't think needs to be addressed yet for this merge. Great work!

**Comment by DanielleKoduru** [comment]
Thanks so much for the great feedback Pete! 

That is a great point about changing the buttons to "save changes" and "cancel". I think that would make much more sense. I will go ahead and add those changes to the names and push them up.

**Review by adelazalewski — APPROVED** [review]
All looks great! Thanks so much for your work. I aslo paid attention to your stakeholder demo and o think it looks great!
Great job and please let me know if I can be of any use at any point ! 
Are you still working with Priyanka or by yourself ?

**Comment by rmscrlos** [comment]
Great Work! I went through the code and everything looks phenomenal. I have nothing to point out. I believe Pete brought up a good point. Other than that, splendid work.

**Comment by DanielleKoduru** [comment]
Thank you Adela. I am working with Priyanka, she is a great teammate. We will continue to work on additional changes from the stakeholder as well.

**Comment by DanielleKoduru** [comment]
Thank you Carlos!

**Comment by adelazalewski** [comment]
> Thank you Adela. I am working with Priyanka, she is a great teammate. We will continue to work on additional changes from the stakeholder as well.

That's awesome i'm so happy you're getting along and being so efficient! Go team!

**Pull request merged**
