### PR TITLE
Mentor form deficiencies

### PR DESCRIPTION
**Pull request by LittleBoGeek**
Updated some of the noted deficiencies in the mentor form.  The mentor registration form can now be navigated by clicking on the individual steps. The back button was renamed to previous as suggested.

### CODE REVIEW

**Review by Brodt7258 — DISMISSED** [review]
definitely a ux improvement, very nice

**Review by PaulMEdwards — APPROVED** [review]
Thank you so much for fixing these issues @LittleBoGeek!

**Review by Brodt7258 — APPROVED** [review]
still looks great after changes, still approved.

**Review by PaulMEdwards — APPROVED** [review]
Re-applying approval after talking Nadia through merge conflict locally in VS Code.

**Pull request merged**
