### PR TITLE
Feature/add user form

### PR DESCRIPTION
**Pull request by aperez9423**
# Short Description

Created the Add User Form and implemented a toggle to control the visibility of the form.

## Rationale/purpose of the feature

This feature will allow administrators to add users.

## Link to relevant User Story

As an admin, I want to be able to add users, so administration can create user profiles.
https://trello.com/b/7MXzlw7m/labs-pt20-vbb-team-b

## Optional: Screenshot(s) of intended state of feature, wire-frame(s), flowchart

Screen Shot 2021-06-17 at 7 28 09 PM

Screen Shot 2021-06-17 at 7 28 17 PM

## Checklist for author and reviewers

- [x] Commits are well named and descriptive
- [x] PR is focused on a single problem, is small enough and easy to review
- [x] PR requests were sent to multiple reviewers
- [ ] PR is reviewed by more than one team member
- [x] Code is consistently formatted
- [x] Code is suitably commented on
- [x] There is no duplicate code
- [x] Code tries to follow best practices
- [ ] Decide with reviewers if this PR should have tests before merging

### CODE REVIEW

**Review by dtebo — APPROVED** [review]
Excellent work. Your code is clean and concise. I also liked that you used the ternary operator for showing and hiding the form.

**Review by sdkramer — COMMENTED** [review]
In src/components/Admin/Admin.js:
there is 'onclick' in line 182, and 'onClick' in line 184--
is that correct?

**Comment by dtebo** [comment]
> In src/components/Admin/Admin.js:
> there is 'onclick' in line 182, and 'onClick' in line 184--
> is that correct?

Wow. How did I miss that? Good catch. I wonder why the duplicate onclick events.

**Comment by aperez9423** [comment]
Thanks for catching that! I will definitely fix that!

**Review by sdkramer — APPROVED** [review]
Looks good to merge--thanks for your work.

**Pull request merged**
