### PR TITLE
Created Expandable Rows

### PR DESCRIPTION
**Pull request by dtebo**
# PR Title: Created Expandable Rows

## Link to relevant user story:

https://trello.com/c/alRwUYWL/42-create-accordion-style-parent-component-to-nest-form-inside-of

### Optional: Screenshots of intended state of feature, wireframe, flowchart

https://imgur.com/a/51JrbcF

# Checklist for author and reviewers:

- Commits are well named and descriptive
- PR is focused on a single problem, is small enough and easy to review
- PR requests were sent to multiple reviewers
- PR is reviewed by more than one team member
- Code is consistenty formatted
- Code is suitably commented on
- There is no duplicate code
- Code tries to follow best practices
- Decide with reviewers if this PR should have tests before merging

### CODE REVIEW

**Comment by sdkramer** [comment]
Looks good.  There are a few things I do not understand, so I am reading the docs on the antd table, to understand the code better. 
Possibly a screen shot of the rendered table could be included in the PR. That would help me at least.

**Comment by dtebo** [comment]
> Looks good. There are a few things I do not understand, so I am reading the docs on the antd table, to understand the code better.
> Possibly a screen shot of the rendered table could be included in the PR. That would help me at least.

Ok, I will add a screenshot. Thank you for the suggestion.

**Comment by Sonyei** [comment]
Could you provide some detail on the decision to place the accordions inside of a table rather than a div? I'm just not quite sure how the accordions open on a table, whereas I know that they open when you click on the title/name if they're just in a div. Is the functionality the same, or does the user need to click in a specific area to render the hidden attributes?

**Comment by dtebo** [comment]
> Could you provide some detail on the decision to place the accordions inside of a table rather than a div? I'm just not quite sure how the accordions open on a table, whereas I know that they open when you click on the title/name if they're just in a div. Is the functionality the same, or does the user need to click in a specific area to render the hidden attributes?

Honestly, the decision was just based on the fact that it was simple to implement as it was already built into the table. However, it does require the user to click on a specific area (the expand/collapse button) in order to reveal the form. I will look into any potential methods to modify that behavior because I do agree that having the option to click on the row to reveal the form would be helpful.

**Comment by Sonyei** [comment]
> Honestly, the decision was just based on the fact that it was simple to implement as it was already built into the table. However, it does require the user to click on a specific area (the expand/collapse button) in order to reveal the form. I will look into any potential methods to modify that behavior because I do agree that having the option to click on the row to reveal the form would be helpful.

This could be an area that we pair program on and learn how to implement the antd components together, if you'd like.

**Comment by dtebo** [comment]
> > Honestly, the decision was just based on the fact that it was simple to implement as it was already built into the table. However, it does require the user to click on a specific area (the expand/collapse button) in order to reveal the form. I will look into any potential methods to modify that behavior because I do agree that having the option to click on the row to reveal the form would be helpful.
> 
> This could be an area that we pair program on and learn how to implement the antd components together, if you'd like.

Sure! We could do that tomorrow if you would like. What time would work for you?

**Comment by Sonyei** [comment]
> Sure! We could do that tomorrow if you would like. What time would work for you?

I'll be available any time after 4pm EST until about 4am EST. Does that time frame work for you?

**Pull request merged**
