### PR TITLE
popups redesigned using antd instead of material-ui

### PR DESCRIPTION
**Pull request by priyanka10it**
# Short Description
This is the change related to #111. Popup messages were designed using material-ui. Since the entire project is designed using antd library and also received feedbacks from team mates, Popup messages are redesigned using antd.

## Rationale/purpose of the feature
To maintain design consistency of the entire project using same library(i.e. antd)

## Link to relevant User Story

[Add visual showing pending changes for all computers on computer view](https://trello.com/c/QpGmjLKl/36-add-visual-showing-pending-changes-for-all-computers-on-computer-view)

Optional attachments here

## Checklist for author and reviewers

- [ ] Commits are well named and descriptive
- [ ] PR is focused on a single problem, is small enough and easy to review
- [ ] PR requests were sent to multiple reviewers
- [ ] PR is reviewed by more than one team member
- [ ] Code is consistently formatted
- [ ] Code is suitably commented on
- [ ] There is no duplicate code
- [ ] Code tries to follow best practices
- [ ] Decide with reviewers if this PR should have tests before merging

### CODE REVIEW

**Comment by rmscrlos** [comment]
Code looks good and simple to read. Also, UI looks great. Great job 👏

**Review by petevs — APPROVED** [review]
Looks and works great Priyanka! Great job switching that over to ant design! Code also seems cleaner which is nice!

**Comment by priyanka10it** [comment]
> Code looks good and simple to read. Also, UI looks great. Great job 👏

Thanks Carlos

**Comment by priyanka10it** [comment]
> Looks and works great Priyanka! Great job switching that over to ant design! Code also seems cleaner which is nice!

Thank you Pete

**Review by DanielleKoduru — APPROVED** [review]
It looks great Priyanka. Great job switching it over to ant design, the code looks really clean and is easy to read. Thanks for all your hard work.

**Comment by priyanka10it** [comment]
> It looks great Priyanka. Great job switching it over to ant design, the code looks really clean and is easy to read. Thanks for all your hard work.

Thank you so much Danielle

**Review by rmscrlos — APPROVED** [review]

**Pull request merged**
