### PR TITLE
Added button color change when user record is edited but not saved

### PR DESCRIPTION
**Pull request by dtebo**
# Short Description

Added button color change when user record is edited but not saved

## Rationale/purpose of the feature

Allows Admin to quickly identify when a user record has been edited, but not saved

## Link to relevant User Story

[Change Button Color when User Record Unsaved](https://trello.com/c/PPeYpqr7/75-change-button-color-when-user-record-unsaved)

## Optional: Screenshot(s) of intended state of feature, wire-frame(s), flowchart

[Screenshot](https://imgur.com/a/3TVYdXm)

## Checklist for author and reviewers

- [ ] Commits are well named and descriptive
- [ ] PR is focused on a single problem, is small enough and easy to review
- [ ] PR requests were sent to multiple reviewers
- [ ] PR is reviewed by more than one team member
- [ ] Code is consistently formatted
- [ ] Code is suitably commented on
- [ ] There is no duplicate code
- [ ] Code tries to follow best practices
- [ ] Decide with reviewers if this PR should have tests before merging

### CODE REVIEW

**Review by aperez9423 — COMMENTED** [review]
Thank you for working on this! The stakeholder wanted our button to match the other teams styling. I believe they had a white background and blue text when the form was not yet ready to submit and turned blue with white text when it was ready to submit. You can look at Team A's demo for exact colors but I think it would be best if we change the button styling to match theirs that way the app is more cohesive.

**Comment by dtebo** [comment]
> Thank you for working on this! The stakeholder wanted our button to match the other teams styling. I believe they had a white background and blue text when the form was not yet ready to submit and turned blue with white text when it was ready to submit. You can look at Team A's demo for exact colors but I think it would be best if we change the button styling to match theirs that way the app is more cohesive.

You're very welcome. Ok, I thought I had said that he wanted it to be white when editing, but not yet saved. I had a hard time hearing him last night. Thank you for clarifying what he was asking. I appreciate it. I went ahead and pushed the updated color scheme. Can you take another look for me?

**Review by aperez9423 — APPROVED** [review]
Yes! I think that is much closer to the other teams! Looks good!

**Comment by dtebo** [comment]
> Yes! I think that is much closer to the other teams! Looks good!

Thank you! I appreciate it.

**Review by sdkramer — APPROVED** [review]
Thanks for both of your comments. 
The changes make our feature aligned with the styling used by team A on the calendar.

**Comment by dtebo** [comment]
> Thanks for both of your comments.
> The changes make our feature aligned with the styling used by team A on the calendar.

You're welcome. Thank you!

**Pull request merged**
