### PR TITLE
added student edit form to the accordion and added dynamic styling capability to the student edit form

### PR DESCRIPTION
**Pull request by dtebo**
# Short Description

Implemented accordion and added the student edit form to it. Also added dynamic styling capability to the student edit form.
Update - Removed student edit form in favor of using the new form that was built.

## Rationale/purpose of the feature

The purpose of the accordion is to allow administrators to edit student records.

## Link to relevant User Story

[Create Accordion style parent component to nest form inside of](https://trello.com/c/alRwUYWL/42-create-accordion-style-parent-component-to-nest-form-inside-of)

## Optional: Screenshot(s) of intended state of feature, wire-frame(s), flowchart

https://imgur.com/a/6ABnAaQ

## Checklist for author and reviewers

- [ ] Commits are well named and descriptive
- [ ] PR is focused on a single problem, is small enough and easy to review
- [ ] PR requests were sent to multiple reviewers
- [ ] PR is reviewed by more than one team member
- [ ] Code is consistently formatted
- [ ] Code is suitably commented on
- [ ] There is no duplicate code
- [ ] Code tries to follow best practices
- [ ] Decide with reviewers if this PR should have tests before merging

### CODE REVIEW

**Review by sdkramer — COMMENTED** [review]
In src/components/StudentInfo/StudentInfoEdit.js:
is 'lyout' on lines 10 and 17 correct, or a typo?

**Comment by dtebo** [comment]
> In src/components/StudentInfo/StudentInfoEdit.js:
> is 'lyout' on lines 10 and 17 correct, or a typo?

It's correct. I used that because they already used the name layout in the upper portion of the file.

**Comment by sdkramer** [comment]
OK. Then looks ready for merge--I will go and approve.

**Review by sdkramer — APPROVED** [review]
Looks ready to merge.

**Comment by dtebo** [comment]
> Looks ready to merge.

Thank you! I will merge it as soon as I get another reviewer to approve.

**Review by aperez9423 — APPROVED** [review]
I also thought that lyout was a typo. Maybe you could change it to be a bit more specific with the next pull request. Looks good to merge though.

**Pull request merged**
