### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by sdkramer**
This is a Pull Request template for the use of Labs PT20 - VBB Team B, based on the PR template rubric:
[https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da](url)
Created by SK

### CODE REVIEW

**Comment by aperez9423** [comment]
Thank you for creating the PR template for us. But, it looks like the permissions have not been changed to allow others to view the link. Could you change the permissions to allow us to view and edit? That way all of us can access the Pull Request when needed.

**Review by dtebo — APPROVED** [review]
Looks good. It contains all of the relevant information that Daniel suggested to us. Great work!

**Review by aperez9423 — APPROVED** [review]
Thought the link was the template you created. But, the template looks great! I created a notion version in case anyone wants to save it for future reference. The link is as follows: https://www.notion.so/PR-Template-2078c610050247f3861ff486d96782d1

**Comment by sdkramer** [comment]
Thanks for the notion link. The link I had was just to the PR template rubric.

**Pull request merged**
