### PR TITLE
Mentee form

### PR DESCRIPTION
**Pull request by MichaelS42**
deleted yup from package.json and deleted changes to StudentInfo

### CODE REVIEW

**Review by Brodt7258 — APPROVED** [review]
looks good. ready to merge and then begin incorporating redux.

**Review by Brodt7258 — APPROVED** [review]

**Review by PaulMEdwards — CHANGES_REQUESTED** [review]
Looks like the `yarn.lock` changes were due to addition of `yup` dependency, which was subsequently removed... Perhaps these `yarn.lock` file changes should be abandoned/reverted @MichaelS42?

**Review by PaulMEdwards — APPROVED** [review]
Approved since `yarn.lock` file changes were reverted manually.

**Review by Brodt7258 — APPROVED** [review]
reapprove!

**Pull request merged**
