### PR TITLE
Added role field to the user edit form

### PR DESCRIPTION
**Pull request by dtebo**
# Short Description

Added role field to the user edit form

## Rationale/purpose of the feature

Enables an Admin to edit a user's role

## Link to relevant User Story

[Missing Role field in Create New User form](https://trello.com/c/b1JfXgPk/73-missing-role-field-in-create-new-user-form)

## Optional: Screenshot(s) of intended state of feature, wire-frame(s), flowchart

[Screenshot](https://imgur.com/a/1uDDiLZ)

## Checklist for author and reviewers

- [ ] Commits are well named and descriptive
- [ ] PR is focused on a single problem, is small enough and easy to review
- [ ] PR requests were sent to multiple reviewers
- [ ] PR is reviewed by more than one team member
- [ ] Code is consistently formatted
- [ ] Code is suitably commented on
- [ ] There is no duplicate code
- [ ] Code tries to follow best practices
- [ ] Decide with reviewers if this PR should have tests before merging

### CODE REVIEW

**Review by sdkramer — COMMENTED** [review]
Thanks for all your work!
Two questions: is there also a headmaster role? do we want to use admin.less rather than admin.css?

**Comment by dtebo** [comment]
> Thanks for all your work!
> Two questions: is there also a headmaster role? do we want to use admin.less rather than admin.css?

You're very welcome. There is a headmaster role. I just forgot to add it. I apologize. Regarding using admin.less versus admin.css. This only shows admin.css because this branch was created prior to Angelika's change to admin.less. Once merged, it should show the admin.less file instead. I will go ahead and pull main into this branch just to be sure.

**Review by aperez9423 — APPROVED** [review]
Thank you Sean for catching the missing role! Everything looks good to merge now. Great job Darren!

**Comment by dtebo** [comment]
> Thank you Sean for catching the missing role! Everything looks good to merge now. Great job Darren!

Thank you! I'm glad that I was able to get this completed.

**Review by sdkramer — APPROVED** [review]
Thanks for clarifying about the less vs css files.
Looks good and ready for merging.

**Pull request merged**
